Thiri-Khit-GymManagementSystem/Controllers/MembershipController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System.Data;
using System.Data.SqlClient;
using Thiri_Khit_GymManagementSystem.Models;

namespace Thiri_Khit_GymManagementSystem.Controllers;

public class MembershipController : Controller
{
    private readonly IConfiguration _configuration;
    private readonly AppDbContext _appDbContext;

    public MembershipController(IConfiguration configuration, AppDbContext appDbContext)
    {
        _configuration = configuration;
        _appDbContext = appDbContext;
    }

    [ActionName("MembershipManagement")]
    public IActionResult Index()
    {
        try
        {
            if (HttpContext.Session.GetString("id") is null)
            {
                return RedirectToAction("LoginPage", "User");
            }

            string query = @"SELECT Users.UserName,
Membership_Plan.PlanName, Membership_Plan.Price,
Membership.MembershipId, Membership.StartDate, Membership.EndDate
FROM Membership
INNER JOIN Membership_Plan ON Membership.MembershipPlanId = Membership_Plan.MembershipPlanId
INNER JOIN Users ON Users.UserId = Membership.UserId
ORDER BY Membership.MembershipId DESC";
            SqlConnection conn = new(_configuration.GetConnectionString("DbConnection"));
            conn.Open();
            SqlCommand cmd = new(query, conn);
            SqlDataAdapter adapter = new(cmd);
            DataTable dt = new();
            adapter.Fill(dt);
            conn.Close();

            string jsonStr = JsonConvert.SerializeObject(dt);
            List<MembershipResponseModel> lst = JsonConvert.DeserializeObject<List<MembershipResponseModel>>(jsonStr)!;

            return View(lst);
        }
        catch (Exception ex)
        {
            throw new Exception(ex.Message);
        }
    }

    public async Task<IActionResult> CreateMembership()
    {
        try
        {
            if (HttpContext.Session.GetString("id") is null)
            {
                return RedirectToAction("LoginPage", "User");
            }

            List<UserDataModel> users = await _appDbContext.Users
                .Where(x => x.UserRole != "admin")
                .ToListAsync();
            List<MembershipPlanDataModel> plans = await _appDbContext.MembershipPlan.ToListAsync();

            CreateMembershipResponseModel responseModel = new()
            {
                Users = users,
                Plans = plans
            };

            return View(responseModel);
        }
        catch (Exception ex)
        {
            throw new Exception(ex.Message);
        }
    }

    [HttpPost]
    public async Task<IActionResult> Save(MembershipDataModel dataModel)
    {
        try
        {
            await _appDbContext.Membership.AddAsync(dataModel);
            int result = await _appDbContext.SaveChangesAsync();

            if (result > 0)
            {
                TempData["success"] = "Creating Successful!";
            }
            else
            {
                TempData["error"] = "Creating Fail!";
            }
            return RedirectToAction("MembershipManagement");
        }
        catch (Exception ex)
        {
            throw new Exception(ex.Message);
        }
    }

    public async Task<IActionResult> EditMembership(long id)
    {
        try
        {
            if (HttpContext.Session.GetString("id") is null)
            {
                return RedirectToAction("LoginPage", "User");
            }

            MembershipDataModel? membership = await _appDbContext.Membership
                .FirstOrDefaultAsync(x => x.MembershipId == id);

            List<MembershipPlanDataModel> plans = await _appDbContext.MembershipPlan
                .ToListAsync();

            List<UserDataModel> users = await _appDbContext.Users
                .Where(x => x.UserRole != "admin")
                .ToListAsync();

            EditMembershipResponseModel responseModel = new()
            {
                Membership = membership,
                Users = users,
                Plans = plans
            };

            return View(responseModel);
        }
        catch (Exception ex)
        {
            throw new Exception(ex.Message);
        }
    }

    [HttpPost]
    public async Task<IActionResult> Update(MembershipDataModel dataModel)
    {
        try
        {
            MembershipDataModel? membership = await _appDbContext.Membership
                .FirstOrDefaultAsync(x => x.MembershipId == dataModel.MembershipId);
            if (membership is null)
            {
                TempData["error"] = "Updating Fail!";
                return RedirectToAction("MembershipManagement");
            }

            membership.MembershipPlanId = dataModel.MembershipPlanId;
            membership.UserId = dataModel.UserId;
            membership.StartDate = dataModel.StartDate;
            membership.EndDate = dataModel.EndDate;
            int result = await _appDbContext.SaveChangesAsync();

            if (result > 0)
            {
                TempData["success"] = "Updating Successful!";
            }
            else
            {
                TempData["error"] = "Updating Fail!";
            }

            return RedirectToAction("MembershipManagement");
        }
        catch (Exception ex)
        {
            throw new Exception(ex.Message);
        }
    }

    public async Task<IActionResult> DeleteMembership(long id)
    {
        try
        {
            if (HttpContext.Session.GetString("id") is null)
            {
                return RedirectToAction("LoginPage", "User");
            }

            MembershipDataModel? membership = await _appDbContext.Membership
                .FirstOrDefaultAsync(x => x.MembershipId == id);
            if (membership is null)
            {
                TempData["error"] = "Deleting Fail!";
                return RedirectToAction("MembershipManagement");
            }

            _appDbContext.Membership.Remove(membership);
            int result = await _appDbContext.SaveChangesAsync();

            if (result > 0)
            {
                TempData["success"] = "Deleting Successful!";
            }
            else
            {
                TempData["error"] = "Deleting Fail!";
            }
            return RedirectToAction("MembershipManagement");
        }
        catch (Exception ex)
        {
            throw new Exception(ex.Message);
        }
    }
}

Thiri-Khit-GymManagementSystem/Controllers/MembershipPlanController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Thiri_Khit_GymManagementSystem.Models;

namespace Thiri_Khit_GymManagementSystem.Controllers;

public class MembershipPlanController : Controller
{
    private readonly AppDbContext _appDbContext;

    public MembershipPlanController(AppDbContext appDbContext)
    {
        _appDbContext = appDbContext;
    }

    [ActionName("MembershipPlanManagement")]
    public async Task<IActionResult> Index()
    {
        try
        {
            if (HttpContext.Session.GetString("id") is null)
            {
                return RedirectToAction("LoginPage", "User");
            }

            List<MembershipPlanDataModel> lst = await _appDbContext.MembershipPlan
                .OrderByDescending(x => x.MembershipPlanId)
                .ToListAsync();

            return View(lst);
        }
        catch (Exception ex)
        {
            throw new Exception(ex.Message);
        }
    }

    public IActionResult CreateMembershipPlan()
    {
        if (HttpContext.Session.GetString("id") is null)
        {
            return RedirectToAction("LoginPage", "User");
        }

        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Save(MembershipPlanDataModel dataModel)
    {
        try
        {
            bool isDuplicate = await _appDbContext.MembershipPlan
                 .AnyAsync(x => x.PlanName == dataModel.PlanName.ToLower());
            if (isDuplicate)
            {
                TempData["error"] = "Plan name already exists!";
                return RedirectToAction("MembershipPlanManagement");
            }

            dataModel.PlanName = dataModel.PlanName.ToLower();
            await _appDbContext.MembershipPlan.AddAsync(dataModel);
            int result = await _appDbContext.SaveChangesAsync();

            if (result > 0)
            {
                TempData["success"] = "Creating Successful!";
            }
            else
            {
                TempData["error"] = "Creating Fail!";
            }
            return RedirectToAction("MembershipPlanManagement");
        }
        catch (Exception ex)
        {
            throw new Exception(ex.Message);
        }
    }

    public async Task<IActionResult> EditMembershipPlan(long id)
    {
        try
        {
            if (HttpContext.Session.GetString("id") is null)
            {
                return RedirectToAction("LoginPage", "User");
            }

            MembershipPlanDataModel? membershipPlan = await _appDbContext.MembershipPlan
                .FirstOrDefaultAsync(x => x.MembershipPlanId == id);

            return View(membershipPlan);
        }
        catch (Exception ex)
        {
            throw new Exception(ex.Message);
        }
    }

    [HttpPost]
    public async Task<IActionResult> Update(MembershipPlanDataModel dataModel)
    {
        try
        {
            bool isDuplicate = await _appDbContext.MembershipPlan
                .AnyAsync(x => x.PlanName == dataModel.PlanName && x.MembershipPlanId != dataModel.MembershipPlanId);
            if (isDuplicate)
            {
                TempData["error"] = "Plan name already exists!";
                return RedirectToAction("MembershipPlanManagement");
            }

            MembershipPlanDataModel? membershipPlan = await _appDbContext.MembershipPlan
                .FirstOrDefaultAsync(x => x.MembershipPlanId == dataModel.MembershipPlanId);

            if (membershipPlan is null)
            {
                TempData["error"] = "Updating Fail!";
                return RedirectToAction("MembershipPlanManagement");
            }

            membershipPlan.PlanName = dataModel.PlanName;
            membershipPlan.Price = dataModel.Price;
            int result = await _appDbContext.SaveChangesAsync();

            if (result > 0)
            {
                TempData["success"] = "Updating Successful!";
            }
            else
            {
                TempData["error"] = "Updating Fail!";
            }

            return RedirectToAction("MembershipPlanManagement");
        }
        catch (Exception ex)
        {
            throw new Exception(ex.Message);
        }
    }

    public async Task<IActionResult> Delete(long id)
    {
        if (HttpContext.Session.GetString("id") is null)
        {
            return RedirectToAction("LoginPage", "User");
        }

        MembershipPlanDataModel? membershipPlan = await _appDbContext.MembershipPlan
            .FirstOrDefaultAsync(x => x.MembershipPlanId == id);
        if (membershipPlan is null)
        {
            TempData["error"] = "Deleting Fail!";
            return RedirectToAction("MembershipPlanManagement");
        }

        _appDbContext.MembershipPlan.Remove(membershipPlan);
        int result = await _appDbContext.SaveChangesAsync();

        if (result > 0)
        {
            TempData["success"] = "Deleting Successful!";
        }
        else
        {
            TempData["error"] = "Deleting Fail!";
        }
        return RedirectToAction("MembershipPlanManagement");
    }
}

Thiri-Khit-GymManagementSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Thiri_Khit_GymManagementSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Thiri_Khit_GymManagementSystem.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Gym Management System</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="UserManagement">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MembershipPlan" asp-action="MembershipPlanManagement">Membership Plan</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Membership" asp-action="MembershipManagement">Membership</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CheckInCheckOut" asp-action="CheckInCheckOutManagement">Check In Check Out</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="ProfileSetting">Profile Setting</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("scripts", required: false)
</body>
</html>